### ISSUE TITLE
Método booleano verificarMovimiento()

### ISSUE THREAD

**Issue by JeanCarlosSC** [JeanCarlos911/candy-crush#10]
### Descripción general 🌐 
Este método a grandes rasgos debe validar 2 cosas:
- Si forma una fila o columna de dulces con el movimiento.
- Verificar que no haya insertado movimiento inválido (en diagonal o una ficha que no sea cercana a la otra).
Devuelve true si el movimiento es válido (es decir si forma una fila o columna de dulces y si el movimiento es válido), de lo contrario retorna false.

### Nota:
En Candy Crush no se forman diagonales y los movimientos diágonales son inválidos.

**Comment by ghost** [comment]
Esta logica de verificar que el movimiento no sea en diagonal o no sea una ficha cercana esta en la validacion que hace el meodo moverDulce(int x1,int y1,int x2,int y2), verifica que ell movimiento sea en x o en y, y la diferencia de la posicion no puede ser mayor a uno

**Comment by JeanCarlosSC** [comment]
Una  manera posible podría ser q la distancia máxima sea 1 y que si es una distancia vertical, entonces no puede haber horizontal y viceversa. De esta manera se podrían evaluar tanto filas, columnas y diagonales :+1:
