### ISSUE TITLE
Posible correccion del metodo para hacer revision por favor

### ISSUE THREAD

**Issue by ghost** [JeanCarlos911/candy-crush#7]
Mando a revision la posible correccion del metodo hayFila(), en caso de ser aprobado se realizara la misma correccion al metodo hay columna
![image](https://user-images.githubusercontent.com/53267735/85203268-3036de80-b2d2-11ea-8160-2201e6e1787c.png)

**Comment by JeanCarlosSC** [comment]
#### Observación 🍬 
- Cuando cambia de fila (en el último condicional), debe resetear también el contador de dulces, sino tomará todas las filas como si fueran la misma (es decir, se podría formar filas de dulces donde dos están al final de una fila y el otro al inicio de la que sigue) 👍
